package methods

import "text/template"

//PkgTmpl - переменная содержит шаблон на основе которого генерируются шапка файла
//  Параметры шаблона:
//   - .Package — название пакета в котором располагаются результаты генерации
//   - .StringArray — название переменной хранящей массив строк
var PkgTmpl = template.Must(template.New("").Parse(`
//{{.FileName}} is auto generated by utility enummethods. DO NOT EDIT
//This file have some type methods implementing the Enumerator and json.Marshaler, json.Unmarshaler interfaces.
package {{.Package}}

import (
	{{if not .WithArray}}
	"strings"{{end}}
	"github.com/ivi81/enummethods/enumerator"
)
`))
