
//objecttype_enummethods.go is auto generated by utility enummethods. DO NOT EDIT
//This file have some type methods implementing the Enumerator and json.Marshaler, json.Unmarshaler interfaces.
package withstringarray

import (
	
	"github.com/ivi81/enummethods/enumerator"
)


//IsValid проверка корректности значения
//Реализует интерфейс Validator
func (m ObjectType) IsValid() bool {

	switch m {
	case
		HIVECASE,
		HIVECASEAPI1,
		HIVEARTIFACT,
		HIVEARTIFACTAPI1,
		HIVETASK,
		HIVETASKAPI1,
		HIVETASKLOG,
		HIVETASKLOGAPI1,
		HIVEALERT,
		HIVEALERTAPI1,
		HIVEORG,
		HIVEORGAPI1:
		return true
	}
	return false
}


//MarshalJSON - реализует метод интерфейса json.Marshaler
func (m ObjectType) MarshalJSON() ([]byte, error) {
	return enumerator.MarshalJSON(m)
}

//UnmarshalJSON - реализует метод интерфейса json.UnMarshaler
func (m *ObjectType) UnmarshalJSON(data []byte) error {
	return enumerator.UnmarshalJSON(m, data)
}


//MarshalYAML - реализует метод интерфейса yaml.Marshaler
func (m ObjectType) MarshalYAML() (interface{}, error) {
	return enumerator.MarshalYAML(m)
}

//UnmarshalYAML - реализует метод интерфейса yaml.UnMarshaler
func (m *ObjectType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	return enumerator.UnmarshalYAML(m, unmarshal)
}


//String конвертация значения типа в строку. 
//Реализует интерфейс Stringer
func (m ObjectType) String() string {
	if m.IsValid() {
		return objectType[m]
	}
	return ""
}


//SetValue - конвертация строки в значение перечислимого типа.
//Реализует интерфейс Unstringer
func (m *ObjectType) SetValue(s string) bool {
	for i, v := range objectType {
		if v == s {
			*m = ObjectType(i)
			return true
		}
	}
	return false
}
