// Code generated by "stringer -type=TestEnum"; DO NOT EDIT.

package testcons

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[First-0]
	_ = x[Second-1]
	_ = x[Third-2]
	_ = x[Fourth-3]
}

const _TestEnum_name = "FirstSecondThirdFourth"

var _TestEnum_index = [...]uint8{0, 5, 11, 16, 22}

func (i TestEnum) String() string {
	if i < 0 || i >= TestEnum(len(_TestEnum_index)-1) {
		return "TestEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TestEnum_name[_TestEnum_index[i]:_TestEnum_index[i+1]]
}
